// One-shot generator for tests/data/2d/delaunay_ref/*.txt.
//
// Builds against a real geogram checkout and dumps, for each of several deterministic random
// point sets, the input points AND geogram's Delaunay triangulation of them. The reference files
// are self-contained (they carry the points), so the unit test never has to reproduce this RNG.
//
// This is NOT part of the VolumeRemesher build; it is run by hand when the references need
// regenerating. See tests/data/2d/delaunay_ref/README.md.

#include <geogram/basic/common.h>
#include <geogram/delaunay/delaunay.h>

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

// Must match Rnd in tests/unit_tests_2d.cpp.
struct Rnd
{
    uint64_t s;
    explicit Rnd(uint64_t seed)
        : s(seed ? seed : 0x9E3779B97F4A7C15ull)
    {}
    uint64_t next()
    {
        s ^= s << 13;
        s ^= s >> 7;
        s ^= s << 17;
        return s;
    }
    double unit() { return double(next() >> 11) * (1.0 / 9007199254740992.0); }
};

int main(int argc, char** argv)
{
    GEO::initialize();
    const std::string outdir = (argc > 1) ? argv[1] : ".";

    struct Case
    {
        const char* name;
        uint32_t n;
        uint64_t seed;
    };
    const Case cases[] = {
        {"random_00010", 10, 0x1111u},   {"random_00050", 50, 0x2222u},
        {"random_00200", 200, 0x3333u},  {"random_01000", 1000, 0x4444u},
        {"random_05000", 5000, 0x5555u},
    };

    for (const Case& c : cases) {
        Rnd rnd(c.seed);
        std::vector<double> pts(2 * size_t(c.n));
        for (auto& v : pts) v = rnd.unit();

        GEO::Delaunay_var d = GEO::Delaunay::create(2, "BDEL2d");
        d->set_vertices(c.n, pts.data());

        // Canonical form: rotate each triangle so its smallest vertex comes first (preserving
        // winding), then sort the list. Makes the comparison independent of triangle numbering.
        std::vector<std::array<uint32_t, 3>> tris;
        tris.reserve(d->nb_cells());
        for (GEO::index_t t = 0; t < d->nb_cells(); t++) {
            uint32_t v[3];
            for (int k = 0; k < 3; k++) v[k] = uint32_t(d->cell_vertex(t, GEO::index_t(k)));
            const int m = (v[0] < v[1]) ? ((v[0] < v[2]) ? 0 : 2) : ((v[1] < v[2]) ? 1 : 2);
            tris.push_back({v[m], v[(m + 1) % 3], v[(m + 2) % 3]});
        }
        std::sort(tris.begin(), tris.end());

        const std::string path = outdir + "/" + c.name + ".txt";
        FILE* f = fopen(path.c_str(), "w");
        if (!f) {
            fprintf(stderr, "cannot write %s\n", path.c_str());
            return 1;
        }
        fprintf(f, "# geogram Delaunay2d reference, generated by gen_delaunay_ref.cpp\n");
        fprintf(f, "# geogram version: %s\n", "b66d107");
        fprintf(f, "POINTS %u\n", c.n);
        // %a prints the exact binary value of the double, so the reference points round-trip
        // bit-for-bit and the comparison cannot be polluted by decimal rounding.
        for (uint32_t i = 0; i < c.n; i++) fprintf(f, "%a %a\n", pts[2 * i], pts[2 * i + 1]);
        fprintf(f, "TRIANGLES %zu\n", tris.size());
        for (const auto& t : tris) fprintf(f, "%u %u %u\n", t[0], t[1], t[2]);
        fclose(f);
        printf("%s: %u points, %zu triangles\n", c.name, c.n, tris.size());
    }
    return 0;
}
