#!/usr/bin/env python3
"""Compute reference SHA-256 hashes for the VolumeRemesher integration tests.

For every model it runs mesh_generator and hashes the generated file with the
same SHA-256 the C++ tests use, so the output of this script is the manifest the
tests read (tests/reference_hashes.txt).

Because the exact predicates make the pipeline deterministic, these hashes must
be identical on every OS. Run this on two platforms (e.g. macOS and Linux) and
diff the manifests to confirm before committing new reference hashes.

Typical use (from the repo root, after building):

    python3 tests/compute_hashes.py --binary build/mesh_generator \
        --models models --out tests/reference_hashes.txt

Add a new test = drop the .off in models/, rerun, commit the updated manifest.
"""

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

# Modes map to a CLI flag and the fixed filename mesh_generator writes.
MODES = {
    "default":    ("",   "volume.msh"),
    "blackfaces": ("-b", "black_faces.off"),
    "skin":       ("-s", "skin.off"),
}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def run_one(binary, model_path, mode, timeout):
    """Run mesh_generator on one model; return (hash, note)."""
    flag, out_name = MODES[mode]
    with tempfile.TemporaryDirectory() as work:
        cmd = [os.path.abspath(binary), os.path.abspath(model_path)]
        if flag:
            cmd.append(flag)
        try:
            subprocess.run(cmd, cwd=work, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, timeout=timeout, check=False)
        except subprocess.TimeoutExpired:
            return None, f"timeout (> {timeout}s)"
        out = os.path.join(work, out_name)
        if not os.path.isfile(out):
            return None, "no output produced"
        return sha256_file(out), "ok"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--binary", required=True, help="path to mesh_generator")
    ap.add_argument("--models", default="models", help="directory of .off models")
    ap.add_argument("--mode", default="default", choices=sorted(MODES),
                    help="output mode to hash (default: default -> volume.msh)")
    ap.add_argument("--timeout", type=float, default=120.0,
                    help="per-model timeout in seconds; slower models are skipped")
    ap.add_argument("--out", default=None,
                    help="write the manifest here (default: stdout only)")
    ap.add_argument("--only", nargs="*", default=None,
                    help="only these model filenames (default: every *.off)")
    args = ap.parse_args()

    if not os.path.isfile(args.binary):
        sys.exit(f"error: binary not found: {args.binary}")

    if args.only:
        models = list(args.only)
    else:
        models = sorted(f for f in os.listdir(args.models) if f.endswith(".off"))

    lines = []
    print(f"{'model':24s} {'mode':11s} {'sha256':64s}  note", file=sys.stderr)
    for m in models:
        path = os.path.join(args.models, m)
        if not os.path.isfile(path):
            print(f"{m:24s} {args.mode:11s} {'-':64s}  missing", file=sys.stderr)
            continue
        digest, note = run_one(args.binary, path, args.mode, args.timeout)
        if digest is None:
            print(f"{m:24s} {args.mode:11s} {'-':64s}  SKIP: {note}", file=sys.stderr)
            continue
        print(f"{m:24s} {args.mode:11s} {digest}  {note}", file=sys.stderr)
        lines.append(f"{m}  {args.mode}  {digest}")

    header = (
        "# VolumeRemesher integration-test reference hashes.\n"
        "# Generated by tests/compute_hashes.py. Format: <model.off> <mode> <sha256>\n"
        "# These must be identical on every OS (verified on macOS + Linux).\n"
    )
    manifest = header + "\n".join(lines) + "\n"
    if args.out:
        with open(args.out, "w") as f:
            f.write(manifest)
        print(f"\nwrote {len(lines)} entries to {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(manifest)


if __name__ == "__main__":
    main()
